CREATE TABLE IF NOT EXISTS match_record (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  difficulty VARCHAR(32) NOT NULL DEFAULT '1',
  survived_sec DOUBLE NOT NULL DEFAULT 0,
  kills INT NOT NULL DEFAULT 0,
  player_level INT NOT NULL DEFAULT 1,
  exp INT NOT NULL DEFAULT 0,
  started_at DATETIME NULL,
  ended_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
